/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.game.gui;

import com.game.util.WindowUtil;
import java.awt.event.KeyEvent;

/**
 *
 * @author perfecking
 */
public class ChooseFrame extends javax.swing.JFrame {
    private String usernmae = null;
    /**
     * Creates new form ChooseFrame
     */
    public ChooseFrame() {
        initComponents();
        jrb_science.setSelected(true);
    }

    public ChooseFrame(String username){
        this.usernmae = username;
        initComponents();
        jrb_science.setSelected(true);
    }
    public String getSelection(){
        String selection = "science";
        if(jrb_art.isSelected()){
            selection = "art";
        }else if(jrb_sports.isSelected()){
            selection = "sports";
        }
        return selection;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        chooseBackgroundPanel1 = new com.game.gui.ChooseBackgroundPanel();
        jrb_science = new javax.swing.JRadioButton();
        jrb_art = new javax.swing.JRadioButton();
        jrb_sports = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseBackgroundPanel1.setPreferredSize(new java.awt.Dimension(990, 669));

        buttonGroup1.add(jrb_science);
        jrb_science.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jrb_science.setForeground(new java.awt.Color(255, 255, 255));
        jrb_science.setText("Science");

        buttonGroup1.add(jrb_art);
        jrb_art.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jrb_art.setForeground(new java.awt.Color(255, 255, 255));
        jrb_art.setText("Art");

        buttonGroup1.add(jrb_sports);
        jrb_sports.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jrb_sports.setForeground(new java.awt.Color(255, 255, 255));
        jrb_sports.setText("Sports");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/game/icons/start.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/game/icons/exit.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select A Subject");

        javax.swing.GroupLayout chooseBackgroundPanel1Layout = new javax.swing.GroupLayout(chooseBackgroundPanel1);
        chooseBackgroundPanel1.setLayout(chooseBackgroundPanel1Layout);
        chooseBackgroundPanel1Layout.setHorizontalGroup(
            chooseBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseBackgroundPanel1Layout.createSequentialGroup()
                .addGroup(chooseBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chooseBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(chooseBackgroundPanel1Layout.createSequentialGroup()
                            .addGap(349, 349, 349)
                            .addComponent(jButton1)
                            .addGap(88, 88, 88)
                            .addComponent(jButton2))
                        .addGroup(chooseBackgroundPanel1Layout.createSequentialGroup()
                            .addGap(467, 467, 467)
                            .addGroup(chooseBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jrb_sports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrb_art, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrb_science, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        chooseBackgroundPanel1Layout.setVerticalGroup(
            chooseBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseBackgroundPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jrb_science)
                .addGap(18, 18, 18)
                .addComponent(jrb_art)
                .addGap(18, 18, 18)
                .addComponent(jrb_sports)
                .addGap(99, 99, 99)
                .addGroup(chooseBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseBackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(chooseBackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selection = getSelection();
        this.dispose();
        AnswerFrame frame = new AnswerFrame(usernmae,selection);
        WindowUtil.centre(frame);
        frame.setResizable(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.game.gui.ChooseBackgroundPanel chooseBackgroundPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jrb_art;
    private javax.swing.JRadioButton jrb_science;
    private javax.swing.JRadioButton jrb_sports;
    // End of variables declaration//GEN-END:variables
}
