/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.game.gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author perfecking
 */
public class PlayerScorePanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerScorePanel
     */
    public PlayerScorePanel() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Image image=new ImageIcon("resources/pure.jpg").getImage();
        g.drawImage(image, 0,0,null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_name = new javax.swing.JLabel();
        jl_scores = new javax.swing.JLabel();
        jl_category = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scores", 0, 0, null, java.awt.Color.white));
        setForeground(new java.awt.Color(255, 255, 255));

        jl_name.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jl_name.setForeground(new java.awt.Color(255, 255, 255));
        jl_name.setText("perfecking");

        jl_scores.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jl_scores.setForeground(new java.awt.Color(255, 255, 255));
        jl_scores.setText("Scores:60");

        jl_category.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jl_category.setForeground(new java.awt.Color(255, 255, 255));
        jl_category.setText("Category:Science");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_scores, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jl_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_scores, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_category)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jl_category;
    public javax.swing.JLabel jl_name;
    public javax.swing.JLabel jl_scores;
    // End of variables declaration//GEN-END:variables
}
