/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.game.gui;

import com.game.entity.GameInfo;
import com.game.util.DbHelper;
import com.game.util.WindowUtil;
import java.awt.Frame;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;

/**
 *
 * @author perfecking
 */
public class RecordDialog extends javax.swing.JDialog {
    private String username = null;
    private int scores = 0;
    private String category = null;
    private Frame parent = null;
    /**
     * Creates new form RecordDialog
     */
    public RecordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RecordDialog(Frame parent,boolean  modal,String username,int scores,String category){
        super(parent, modal);
        this.parent = parent;
        this.username = username;
        this.scores = scores;
        this.category = category;
        initComponents();
        initModel();
        initPanel();
    }
    public void initModel(){
        List<GameInfo> list = DbHelper.getRecords();
        GameInfo gameInfo = null;
        TableModel tableModel = jTable1.getModel();
        for(int i=0,j=0;i<list.size()&&i<3&&j<tableModel.getRowCount();j++,i++){
            gameInfo = list.get(i);
            int k=0;
            tableModel.setValueAt(gameInfo.getUsername(), j,k++);
            tableModel.setValueAt(gameInfo.getScores(), j, k++);
            tableModel.setValueAt(gameInfo.getCategory(),j, k++);
        }
    }
    public void initPanel(){
        if(scores==0){
            jl_face.setIcon(new ImageIcon("resources/face3.jpg"));
        }else if(scores==20||scores==40){
            jl_face.setIcon(new ImageIcon("resources/face2.jpg"));
        }else{
            jl_face.setIcon(new ImageIcon("resources/face1.jpg"));
        }
        playerScorePanel1.jl_name.setName(username);
        playerScorePanel1.jl_scores.setText("Scores:"+scores);
        playerScorePanel1.jl_category.setText("Category:"+category);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordBackgroundPanel1 = new com.game.gui.RecordBackgroundPanel();
        jl_face = new javax.swing.JLabel();
        playerScorePanel1 = new com.game.gui.PlayerScorePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jl_face.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/game/icons/face1.jpg"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Score", "Category"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordBackgroundPanel1Layout = new javax.swing.GroupLayout(recordBackgroundPanel1);
        recordBackgroundPanel1.setLayout(recordBackgroundPanel1Layout);
        recordBackgroundPanel1Layout.setHorizontalGroup(
            recordBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordBackgroundPanel1Layout.createSequentialGroup()
                .addGroup(recordBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordBackgroundPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recordBackgroundPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(recordBackgroundPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jl_face)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(playerScorePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        recordBackgroundPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        recordBackgroundPanel1Layout.setVerticalGroup(
            recordBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordBackgroundPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(recordBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_face, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerScorePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(recordBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        recordBackgroundPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordBackgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordBackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GameInfo gameInfo = new GameInfo(username, scores, category);
        DbHelper.save(gameInfo);
        this.dispose();
        parent.dispose();
        LoginFrame frame = new LoginFrame();
        WindowUtil.centre(frame);
        frame.setResizable(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jl_face;
    private com.game.gui.PlayerScorePanel playerScorePanel1;
    private com.game.gui.RecordBackgroundPanel recordBackgroundPanel1;
    // End of variables declaration//GEN-END:variables
}
