/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.game.gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author perfecking
 */
public class RecordBackgroundPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecordBackgroundPanel
     */
    public RecordBackgroundPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Image image=new ImageIcon("resources/background.jpg").getImage();
        g.drawImage(image, 0,0,null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
